apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: storageclass-pvc
spec:
  storageClassName: faster
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
