kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: central1
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-standard
  replication-type: regional-pd
  zones: us-central1-a, us-central1-f
