apiVersion: v1
kind: Pod
metadata:
  name: empty-dir-pod
  labels:
    name: empty-dir-pod
spec:
  containers:
  - name: empty-dir-pod
    image: busybox
    command: ['sh', '-c', 'echo Hello from a Pod && touch /data/foo && ls -l /data && sleep 60']
    volumeMounts:
    - name: scratch
      mountPath: /data		# the volume 'scratch' is mounted into /data
  volumes:
  - name: scratch			# create volume 'scratch' at node location /var/log
    emptyDir: {}
