apiVersion: batch/v1
kind: Job
metadata:
  name: host-path-job
  labels:
    job: host-path-job
spec:
  template:
    spec:
      containers:
      - name: host-path-job
        image: busybox
        command: ['sh', '-c', 'echo Hello from a Job && ls -l /var/log && sleep 60']
        volumeMounts:
        - name: varlog
          mountPath: /var/log
          readOnly: true
      restartPolicy: OnFailure
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
