apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pv-disk-pvc
spec:
  storageClassName: standard
  accessModes:
    - ReadOnlyMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 500Gi
  volumeName: pv-disk

