apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-disk
  labels:
    failure-domain.beta.kubernetes.io/zone: us-central1-a
spec:
  storageClassName: standard
  capacity:
    storage: 500Gi
  accessModes:
    - ReadOnlyMany
  gcePersistentDisk:
    pdName: pv-disk
    readOnly: true
    fsType: ext4
