apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: ip-webapp
  namespace: default
spec:
  maxReplicas: 10
  minReplicas: 3
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: ip-webapp
  targetCPUUtilizationPercentage: 80
