apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: ip-webapp
  namespace: default
spec:
  maxReplicas: 10
  minReplicas: 3
  scaleTargetRef:    # specifies the Deployment which is autoscaled
    apiVersion: apps/v1
    kind: Deployment
    name: ip-webapp
  targetCPUUtilizationPercentage: 80
